name: Deploy MNIST with FastAPI to OCI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OCI_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.OCI_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Test SSH Connection
        run: ssh -T -i ~/.ssh/id_rsa ubuntu@${{ secrets.OCI_HOST }}

      - name: Deploy Application
        run: |
          ssh -T -i ~/.ssh/id_rsa ubuntu@${{ secrets.OCI_HOST }} << 'EOF'
            cd FastAPI_MNIST
            git pull origin main
            docker stop app || true
            docker rm app || true
            docker build -t app .
            docker run -d --name app -p 8000:8000 app
          EOF
        shell: bash